### ISSUE TITLE
Develop the technical task

### ISSUE THREAD

**Issue by akrava** [AI-technologies-for-IR-system/image-search-engine#2]
It is needed to develop "Technical task" and assign roles to each members of team.

We need to create such things:

- [x] technical task 
- [x] list of roles of each team member

**Comment by akravacyber** [comment]
Here is a technical task: https://github.com/AI-technologies-for-IR-system/image-search-engine#technical-task (official doc: https://github.com/AI-technologies-for-IR-system/image-search-engine/blob/master/docs/TZ_image-search-system.doc)
Here is list of roles of each team member https://github.com/AI-technologies-for-IR-system/image-search-engine#role-of-each-team-member

**Comment by akrava** [comment]
Here is a technical task: https://github.com/AI-technologies-for-IR-system/image-search-engine#technical-task (official doc: https://github.com/AI-technologies-for-IR-system/image-search-engine/blob/master/docs/TZ_image-search-system.doc)
Here is list of roles of each team member: https://github.com/AI-technologies-for-IR-system/image-search-engine#role-of-each-team-member
