### ISSUE TITLE
Make design doc and describe architecture of system

### ISSUE THREAD

**Issue by akrava** [AI-technologies-for-IR-system/image-search-engine#9]
We need to create a top-level architecture of our system in order to describe a further scope of work.

What's expected in terms of this issue:
- [x] distinguish modules and describe them
- [x] brief diagram of data flow between modules[^1]
- [x] design a GCP model of the service
- [ ] design a database

[^1]: Moved into modules diagram

**Comment by akrava** [comment]
Top-level modules of system:
![image](https://user-images.githubusercontent.com/13131083/139347749-b8dac371-fb66-4ddc-87e8-09a3720a5f95.png)

**Comment by FireAndBlood12** [comment]
Take a look at the GCP model. ![GCP model](https://user-images.githubusercontent.com/36378202/139336285-57fb945c-9b64-47e2-aa0e-d727015eeb45.png)

**Comment by akrava** [comment]
Cool, thanks @FireAndBlood12 !
